### PR TITLE
removed duplicates from templates

### PR DESCRIPTION
**Pull request by timkenhan**

### CODE REVIEW

**Comment by dolphinoracle** [comment]
the mxflux template package.list files are still blank.

**Comment by timkenhan** [comment]
that is weird, because on my branch, the files themselves are not empty
https://github.com/timkenhan/build-iso-mx/blob/master/Template/mxflux64/package.list
https://github.com/timkenhan/build-iso-mx/blob/master/Template/mxflux32/package.list

**Comment by dolphinoracle** [comment]
hmm that is weird.  the web interface reports "empty file" but viewing the file has contents.   I'm a little leary about taking it into main without verifying the contents of those files.  if they are identical, they shouldn't be part of the commit.  if they had changes, the changes should be visible like the other changes.

**Comment by timkenhan** [comment]
i think it shows empty because there's no difference content wise. after looking further into it, it turns out it was because the mode was changed from 755 to 644. i honestly don't remember making these changes, but 644 seem to be more appropriate for data file.

**Comment by dolphinoracle** [comment]
ok that would do it, and its not obvious in the web interface.

**Pull request merged**
