### PR TITLE
refactoring to allow devuan base; cleanup on the package list

### PR DESCRIPTION
**Pull request by timkenhan**
in the light of peppermint os now having devuan base as one of its options, i was inspired to do something similar. i think it would fit mx linux :)

### CODE REVIEW

**Comment by dolphinoracle** [comment]
upon reviewing this merge request, your changes seem to remove the package.list files for mxflux32 and mxflux64.  

I'm on the fence about adding devuan into our official git repo.  I don't want people to think we are planning to rebase.

the changes to the repo selection in build-iso remove a question that gets asked if the repo mirror isn't defined.   the code is non-functional anyway on MX because we use the deb.debian redirect, but antiX does not.  I would prefer to not see it removed.  code is merged from time to time and I don't want to break anything for antiX.

the change in build-iso that adds these lines at 867- is unnecessary 

apt-get $APT_GET_OPTS upgrade
apt-get $APT_GET_OPTS dist-upgrade

nice de-duplication efforts.  also the keyring verification.  I presume the keyring.gpg key would need downloaded ahead of time.

**Comment by timkenhan** [comment]
> I don't want people to think we are planning to rebase.

i don't think people would mind much that we're following the trend a little bit. :)

> your changes seem to remove the package.list files for mxflux32 and mxflux64.

this is due to the deduplication, seems to have no unique package after it. i can add empty files if it's necessary.

> nice de-duplication efforts.

thanks! i can share the helper script if you want.

> also the keyring verification. I presume the keyring.gpg key would need downloaded ahead of time.

yes, should be provided by whatever repo we're connecting to.

i can split this pr into several pieces to help your review

**Comment by dolphinoracle** [comment]
mxflux32 and mxflux64 package.list files being empty is not correct, even with de-duplication.  since no other package.list file should be installing the fluxbox wm or associated packages.

**Comment by timkenhan** [comment]
> mxflux32 and mxflux64 package.list files being empty is not correct

they may have been removed by mistake then

> the changes to the repo selection in build-iso remove a question that gets asked if the repo mirror isn't defined. the code is non-functional anyway on MX because we use the deb.debian redirect, but antiX does not. I would prefer to not see it removed. code is merged from time to time and I don't want to break anything for antiX.

can there be a good compromise? i think that flexibility for rebasing can be a nice thing to have. i'm thinking maybe have template string so we can keep the same MIRROR

**Comment by dolphinoracle** [comment]
possible the local mirror change is OK.  still thinking about it.  But the "choose DEBIAN_RELEASE" question must remain.  it will be ignored if DEBIAN_RELEASE is defined from an Input file anyway.

LOCAL_MIRROR need set to some default if its not present in a Input file, else the debootstrap may fail.

**Comment by timkenhan** [comment]
DEBIAN_RELEASE shouldn't be an issue, I think, at least for this early phase.

for LOCAL_MIRROR, the fallback value will be present on defaults-system, right?

also, I've confirmed with devuan maintainer that http://$mirror.deb.devuan.org is available (albeit not polished at the moment).

**Comment by dolphinoracle** [comment]
it can be in defaults-system, but it doesn't have to be.  the only reason its there on MX systems is because it was common between some other settings file.

**Comment by dolphinoracle** [comment]
closing this PR as it currently conflicts with other PRs.

**Pull request closed without merging**
