### PR TITLE
some DX improvements

### PR DESCRIPTION
**Pull request by timkenhan**
- enabled keyring inclusion
- added exclude list for chroot, renamed for bootstrap
- corrected README

### CODE REVIEW

**Comment by dolphinoracle** [comment]
please revert change to defaults-system. those items are already present in defaults-system and the values you added will be ignored.

**Comment by timkenhan** [comment]
done!

**Comment by dolphinoracle** [comment]
changes to build-iso script appear to prevent the script from executing beyond stage 0

**Comment by dolphinoracle** [comment]
never mind, its a different change, not these.

**Pull request merged**
